### PR TITLE
update embedding dim

### PR DESCRIPTION
**Pull request by zhaoyang-star**
When Slice the embeddings, we should also update the embedding dims.
Without this pr: 
```
UninitializedLlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096, padding_idx=0)
    (layers): ModuleList(
      (0-30): 31 x CompressedLlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (up_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=3072, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): RMSN()
        (post_attention_layernorm): RMSN()
      )
      (31): CompressedLlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (up_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): RMSN()
        (post_attention_layernorm): RMSN()
      )
    )
    (norm): RMSN()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)
```

With this pr:
```
UninitializedLlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 3072, padding_idx=0)
    (layers): ModuleList(
      (0-30): 31 x CompressedLlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (up_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=3072, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): RMSN()
        (post_attention_layernorm): RMSN()
      )
      (31): CompressedLlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (up_proj): Linear(in_features=3072, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): RMSN()
        (post_attention_layernorm): RMSN()
      )
    )
    (norm): RMSN()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)
```
@pashminacameron @nailimixaM

### CODE REVIEW

**Comment by nailimixaM** [comment]
Thanks for finding this bug @zhaoyang-star! The change looks good, but before merging could you please run `pytest -m experiment` in the tests dir? Just to confirm no breaking changes in end-to-end pipeline

**Comment by zhaoyang-star** [comment]
@nailimixaM 
I ran `pytest -m experiment` and it freezed. Could you give same hint on this? `python -m pytest tests/test_experiments.py::test_opt_125m` has the same issue.
```
/github/sparsity/TransformerCompression# pytest -m experiment
=========================================================== test session starts ============================================================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /github/sparsity/TransformerCompression
configfile: pyproject.toml
plugins: asyncio-0.23.4, forked-1.6.0, anyio-4.2.0, flakefinder-1.1.0, hypothesis-5.35.1, xdist-3.4.0, shard-0.1.2, xdoctest-1.0.2, rerunfailures-12.0
asyncio: mode=strict
collected 30 items / 28 deselected / 2 selected                                                                                            
Running 2 items in this shard

tests/test_experiments.py
```

**Comment by nailimixaM** [comment]
> @nailimixaM I ran `pytest -m experiment` and it freezed. Could you give same hint on this? `python -m pytest tests/test_experiments.py::test_opt_125m` has the same issue.
> 
> ```
> /github/sparsity/TransformerCompression# pytest -m experiment
> =========================================================== test session starts ============================================================
> platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
> rootdir: /github/sparsity/TransformerCompression
> configfile: pyproject.toml
> plugins: asyncio-0.23.4, forked-1.6.0, anyio-4.2.0, flakefinder-1.1.0, hypothesis-5.35.1, xdist-3.4.0, shard-0.1.2, xdoctest-1.0.2, rerunfailures-12.0
> asyncio: mode=strict
> collected 30 items / 28 deselected / 2 selected                                                                                            
> Running 2 items in this shard
> 
> tests/test_experiments.py
> ```

It looks fine to me - should be running in the background, these tests will take 10/20mins depending on your GPU, as they're running end-to-end SliceGPT + PPL + lm eval

**Comment by zhaoyang-star** [comment]
```
python -m pytest -svv tests/test_experiments.py::test_opt_125m
=========================================================== test session starts ============================================================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0 -- /usr/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/bigdata/zhaoyang/github/sparsity/TransformerCompression/.hypothesis/examples')
rootdir: /bigdata/zhaoyang/github/sparsity/TransformerCompression
configfile: pyproject.toml
plugins: asyncio-0.23.4, forked-1.6.0, anyio-4.2.0, flakefinder-1.1.0, hypothesis-5.35.1, xdist-3.4.0, shard-0.1.2, xdoctest-1.0.2, rerunfailures-12.0
asyncio: mode=strict
collected 1 item                                                                                                                           
Running 1 items in this shard: tests/test_experiments.py::test_opt_125m

tests/test_experiments.py::test_opt_125m PASSED

====================================================== 1 passed in 321.68s (0:05:21) ===================================================
```
`tests/test_experiments.py::test_phi_2` is still running.

**Comment by zhaoyang-star** [comment]
The unittest has passed.
```
/TransformerCompression# python -m pytest -svv tests/test_experiments.py
========================================================= test session starts ==========================================================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0 -- /usr/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/bigdata/zhaoyang/github/sparsity/TransformerCompression/.hypothesis/examples')
rootdir: /bigdata/zhaoyang/github/sparsity/TransformerCompression
configfile: pyproject.toml
plugins: asyncio-0.23.4, forked-1.6.0, anyio-4.2.0, flakefinder-1.1.0, hypothesis-5.35.1, xdist-3.4.0, shard-0.1.2, xdoctest-1.0.2, rerunfailures-12.0
asyncio: mode=strict
collected 2 items                                                                                                                      
Running 2 items in this shard: tests/test_experiments.py::test_opt_125m, tests/test_experiments.py::test_phi_2

tests/test_experiments.py::test_opt_125m PASSED
tests/test_experiments.py::test_phi_2 PASSED

==================================================== 2 passed in 8229.49s (2:17:09) ====================================================
```

**Review by nailimixaM — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
